[package]
name = "libpghom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]
name = "pghom"

[dependencies]
pghom = { version = "0.1.0", path = ".." }

[build-dependencies]
cbindgen = "0.24.3"
